services:
  
  mariadb:
    networks:
      - ci
    environment:
        MARIADB_ROOT_PASSWORD: "rootpassword"
        MARIADB_DATABASE: "financialfreedom_testing"
        MARIADB_USER: "dbuser"
        MARIADB_PASSWORD: "dbpassword"

  php:
    networks:
      - ci
    volumes:
      - .:/var/www/html/
    working_dir: /var/www/html/
    depends_on:
      - mariadb

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
      target: base
    networks:
      - ci
    volumes:
      - .:/usr/src/app/:cached
    working_dir: /usr/src/app/

  mailpit:
    image: axllent/mailpit
    networks:
      - ci

networks:
  ci: