services:

  traefik:
    image: traefik:v2.10

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    working_dir: /var/www/html
    depends_on:
      - traefik
      - mariadb

  mariadb:
    image: mariadb:10.11